# Globals
author: Alessandro De Piccoli
title: Colonna
subtitle: Minimal theme

# html specifications
url: ""
baseurl: ""
lang: en

# Theme switcher
disable_theme_switcher: false

enableEmoji: false
paginate: 5
summary_length: 20

# Highlight code
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:   # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
  
# Menu items
menu:
  -
    name: Home
    url: "/"
  -
    name: Posts
    url: "/posts.html"
  -
    name: About
    url: "/about.html"
  -
    name: Tags
    url: "/tags.html"

# Plugins
plugins:
  - jekyll-youtube

# Compress CSS
sass:
  style: compressed

# Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
social_icons:
  -
    icon: "fas fa-envelope"
    title: "E-mail"
    url: "mailto:ale.depi@live.it"
  -
    icon: "fab fa-gitlab"
    title: "GitLab"
    url: "https://gitlab.com/ale-depi/"
  -
    icon: "fab fa-github"
    title: "GitHub"
    url: "https://github.com/ale-depi/"
